### ISSUE TITLE
Too much information in start.sh

### ISSUE THREAD

**Issue by ryppo** [JPro-one/HelloJPro-Maven#5] opened 2018-11-13 09:09 UTC
Using `mvn install jpro:release` creates the wanted zip container.
Issue: The included `start.sh` contains unwanted information.
`JPRO_ARGS` contains `-Djprocp=<unwanted_data>`. This _unwanted_data_ are the absolute paths to the local mvn repository libs.
Obviously, absolute path information should be protected. Means, at maximum there should be relative paths.
**Suggested solution**
Removing `-Djprocp=...` from `PRO_ARGS` seems to have no impact to the application. It could be a solution to simply not putting this information.

**Comment by FlorianKirmaier** [comment] 2018-11-13 10:28
Thank you for the report. I can confirm this problem. 
The problem is limited to the Maven-Plugin.
The wrong jprocp is overwritten slightly later in the script, that's why it doesn't have any direct impact.

**Comment by FlorianKirmaier** [comment] 2018-11-20 16:37
Fixed in the upcoming version 2018.1.9

**Comment by ryppo** [comment] 2018-11-21 09:40
Confirmed. It is fixed in 2018.1.9-SNAPSHOT. Thx

**Closed as completed** 2018-11-21 09:41 UTC
